<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users [
<!ELEMENT users (user+)>
  <!ELEMENT user (name,password,schemas)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
  <!ELEMENT schemas (#PCDATA)>
]>
<users>
	<user>
		<name>user</name>
		<password>123456</password>
		<schemas>CRM_DG_A,ABSP,CRM2_CONF
		</schemas>
	</user>
	<user>
		<name>root</name>
		<password>123456</password>
		<schemas>CRM_DG_A
		</schemas>
	</user>
</users>